import * as THREE from 'three/webgpu'
import * as TSL from 'three/tsl'
import { ssr } from 'three/examples/jsm/tsl/display/SSRNode'
import { traa } from 'three/examples/jsm/tsl/display/TRAANode'
import { lut3D } from 'three/examples/jsm/tsl/display/Lut3DNode'
import { ssgi } from 'three/examples/jsm/tsl/display/SSGINode'
import { bloom } from 'three/examples/jsm/tsl/display/BloomNode'

import React, { Suspense } from 'react'
import { Canvas } from '@react-three/fiber'
import { Loader, useGLTF, OrbitControls, PerspectiveCamera, Stars } from '@react-three/drei'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
function Model({ url }) {
  const { nodes } = useGLTF(url)
  return (
    <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={7}>
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh receiveShadow castShadow geometry={nodes.planet002.geometry} material={nodes.planet002.material} />
        <mesh geometry={nodes.planet003.geometry} material={nodes.planet003.material} />
      </group>
    </group>
  )
}

export default function App() {
  return (
    <>
      <div className="bg" />
          <div className="content"
      dangerouslySetInnerHTML={{
          __html: window.APP_CONFIG?.htmlContent || '',
      }}
          />
      <Canvas dpr={[1.5, 2]} linear shadows>
        <fog attach="fog" args={['#272730', 16, 30]} />
        <ambientLight intensity={0.75 * Math.PI} />
        <PerspectiveCamera makeDefault position={[0, 0, 16]} fov={75}>
          <spotLight
            castShadow
            intensity={2.25 * Math.PI}
            decay={0}
            angle={0.2}
            penumbra={1}
            position={[-25, 20, -15]}
            shadow-mapSize={[1024, 1024]}
            shadow-bias={-0.0001}
          />
        </PerspectiveCamera>
        <Suspense fallback={null}>
          <Model url={`${process.env.PUBLIC_URL}/scene.glb`} />
        </Suspense>
        <OrbitControls autoRotate enablePan={false} enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
        <Stars radius={500} depth={50} count={1000} factor={10} />
      </Canvas>
      <div className="layer" />
      <Loader />
      <a href="https://github.com/drcmda/learnwithjason" className="top-left" children="Github" />
      <a href="https://twitter.com/0xca0a" className="top-right" children="Twitter" />
      <a href="https://github.com/pmndrs/react-three-fiber" className="bottom-left" children="@react-three/fiber" />
    </>
  )
}
