import * as THREE from 'three/webgpu'
import * as TSL from 'three/tsl'
import { ssr } from 'three/examples/jsm/tsl/display/SSRNode'
import { traa } from 'three/examples/jsm/tsl/display/TRAANode'
import { lut3D } from 'three/examples/jsm/tsl/display/Lut3DNode'
import { ssgi } from 'three/examples/jsm/tsl/display/SSGINode'
import { bloom } from 'three/examples/jsm/tsl/display/BloomNode'

import React, { Suspense, useEffect } from 'react'
import { Canvas } from '@react-three/fiber'
import { Loader, useGLTF, OrbitControls, PerspectiveCamera, Stars } from '@react-three/drei'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
function Model({ url }) {
  const { nodes } = useGLTF(url)
  return (
    <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={7}>
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh receiveShadow castShadow geometry={nodes.planet002.geometry} material={nodes.planet002.material} />
        <mesh geometry={nodes.planet003.geometry} material={nodes.planet003.material} />
      </group>
    </group>
  )
}

export default function App() {

  useEffect(() => {
    // Generic reusable jukebox function
    function createJukebox(audioId, sourceId, tracks, options = {}) {
      const audio = document.getElementById(audioId);
      const source = document.getElementById(sourceId);
      if (!audio || !source || !tracks) return;

      let index = Math.floor(Math.random() * tracks.length);

      function playTrack() {
        source.src = tracks[index];
        audio.load();

        // Start at random timestamp? (DiskD mode)
        if (options.randomStart) {
          audio.addEventListener("loadedmetadata", function rs() {
            audio.removeEventListener("loadedmetadata", rs);
            const duration = audio.duration;
            const len = isFinite(duration) ? duration : 3600;
            audio.currentTime = Math.random() * len;
          });
        }

        audio.play().catch(() => {
          // Unlock audio on first user click
          const unlock = () => {
            audio.play();
            document.removeEventListener("click", unlock);
          };
          document.addEventListener("click", unlock);
        });
      }

      audio.addEventListener("ended", () => {
        index = (index + 1) % tracks.length;
        playTrack();
      });

      // Start playback on first user click
      const init = () => {
        playTrack();
        document.removeEventListener("click", init);
      };
      document.addEventListener("click", init);

    }

    // Start DiskC + DiskD players
    const cfg = window.APP_CONFIG;
    createJukebox("DiskC", "DiskCSource", cfg.DiskC, { randomStart: false });
    createJukebox("DiskD", "DiskDSource", cfg.DiskD, { randomStart: true });

  }, []); // runs once

  return (
    <>
          {/* AUDIO PLAYERS */}
          <audio id="DiskC" autoplay crossorigin="anonymous" style={{ display: "none" }}>
          <source id="DiskCSource" type="audio/mpeg" />
          </audio>

          <audio id="DiskD" autoplay crossorigin="anonymous" style={{ display: "none" }}>
          <source id="DiskDSource" type="audio/mpeg" />
          </audio>

      <div className="bg" />
          <div className="content"
      dangerouslySetInnerHTML={{
          __html: window.APP_CONFIG?.htmlContent || '',
      }}
          />
      <Canvas dpr={[1.5, 2]} linear shadows>
        <fog attach="fog" args={['#272730', 16, 30]} />
        <ambientLight intensity={0.75 * Math.PI} />
        <PerspectiveCamera makeDefault position={[0, 0, 16]} fov={75}>
          <spotLight
            castShadow
            intensity={2.25 * Math.PI}
            decay={0}
            angle={0.2}
            penumbra={1}
            position={[-25, 20, -15]}
            shadow-mapSize={[1024, 1024]}
            shadow-bias={-0.0001}
          />
        </PerspectiveCamera>
        <Suspense fallback={null}>
          <Model url={`${process.env.PUBLIC_URL}/scene.glb`} />
        </Suspense>
        <OrbitControls autoRotate enablePan={false} enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
        <Stars radius={500} depth={50} count={1000} factor={10} />
      </Canvas>
      <div className="layer" />
      <Loader />
      <a href="https://mydream42.com/?debug=https://www.upwork.com/freelancers/~0128fbc8be0ee3d65b" className="link top-right" children="Hire ❄️ Me" />
      <a href="https://mydream42.com/?debug=https://x.com/yelizariev" className="link bottom-right" children="Fire 🔥 Me" />
    </>
  )
}
